---
- name: Gather and update facts on the hosts in scope
  setup:
  delegate_to: "{{item}}"
  with_items: "{{groups['ipsec']}}"

- name: add EPEL repo
  yum: name=epel-release
  when: ansible_distribution in ('CentOS', 'Red Hat Enterprise Linux')

- name: ipsec-tools installed
  yum: name=ipsec-tools
  when: ansible_os_family == 'RedHat'
- name: ipsec-tools installed
  apt: name=ipsec-tools
  when: ansible_distribution in ('Debian', 'Ubuntu')

- name: setkey service file created
  template: src=templates/setkey.service dest=/etc/systemd/system/setkey.service
  when: ansible_service_mgr == 'systemd'

- name: setky service enabled
  systemd: name=setkey.service daemon_reload=yes
  when: ansible_service_mgr == 'systemd'

- name: racoon installed
  apt: name=racoon state=present
  when: ansible_distribution in ('Debian', 'Ubuntu') and ipsec_mode == 'ike'
- debug: msg='ipsec_secret={{ipsec_secret}}'
- assert:
    that:
    - ipsec_policy in ('use','require','disable')
    - ipsec_mode in ('ike','setkey')
    - ipsec_secret != 'Your IPSec Secret'

- name: ipsec-tools configuration
  template: src=templates/ipsec-tools.conf dest=/etc/ipsec-tools.conf mode=0700 owner=root
  notify:
  - setkey restart

- name: racoon configuration
  template: src=templates/racoon.conf dest=/etc/racoon/racoon.conf
  when: ipsec_mode == 'ike'
  notify:
  - racoon restart

- name: pre-shared keys file
  template: src=templates/psk.txt dest=/etc/racoon/psk.txt mode=0600
  when: ipsec_mode == 'ike'
  notify:
  - racoon restart

- name: racoon service
  service: name=racoon state=started enabled=yes
  when: ipsec_mode == 'ike'

- name: check if racoon is installed
  when: ipsec_mode == 'setkey'
  service_facts:

- name: disabling racoon service because ipsec_mode is setkey
  service: name=racoon state=stopped enabled=no
  when: "(ipsec_mode == 'setkey') and (ansible_facts.services.racoon is defined)"
  
- name: setkey startup
  lineinfile: dest=/etc/default/setkey line="RUN_SETKEY=yes" regexp="RUN_SETKEY"
  when: ansible_distribution in ('Debian', 'Ubuntu')

- name: setkey service
  service: name=setkey state=started enabled=yes

- debug: msg='*** We have just totally disabled IPSec due to ipsec_policy=disable ***'
  when: ipsec_policy == 'disable'
